pinpoint dependency: tornado<5.0.0 to prevent incompatibilities
in order to prevent this error::

   TypeError: add_accept_handler() takes 2 positional arguments but 3 were given

in tornado==5.0.0 the ioloop parameter was removed:

   add_accept_handler(sck, handle_connection, ioloop)